//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChipAquariumMobileService.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChipAquariumMobileService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   @aquariumId に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertMailTextAquariumIdSection {
            get {
                return ResourceManager.GetString("AlertMailTextAquariumIdSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Water temperature not been received.
        ///
        ///Aquarium ID : @aquariumId
        ///Last Received At : @lastReceivedAt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotBeenReceivedAlertMailText {
            get {
                return ResourceManager.GetString("NotBeenReceivedAlertMailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotBeenReceivedMailTextLastReceivedAtSection {
            get {
                return ResourceManager.GetString("NotBeenReceivedMailTextLastReceivedAtSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Water temperature alert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaterTemperatureAlertMailSubject {
            get {
                return ResourceManager.GetString("WaterTemperatureAlertMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Water temperature exceeds the normal range.
        ///
        ///Aquarium ID : @aquariumId
        ///Current WaterTemperature : @temperature ℃ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaterTemperatureOutOfRangeAlertMailText {
            get {
                return ResourceManager.GetString("WaterTemperatureOutOfRangeAlertMailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaterTemperatureOutOfRangeAlertMailTextTemperatureSection {
            get {
                return ResourceManager.GetString("WaterTemperatureOutOfRangeAlertMailTextTemperatureSection", resourceCulture);
            }
        }
    }
}
